name: Extract Hair Salon Infos
description: Extracts the city and name of the hair salon
inputs:
  index:
    description: Index of the hair salon
    required: true
outputs:
  city:
    description: The city of the hair salon
  name:
    description: The name of the hair salon
runs:
  using: composite
  steps:
    - name: Execute script
      id: extract
      run: |
          start_date="2024-01-28"
          current_date=$(date +%Y-%m-%d)
          number_of_days=$(($(($(date -u -d "$current_date" +"%s") - $(date -u -d "$start_date" +"%s"))) / 86400))
        
          echo "Number of days since $start_date: $number_of_days"
          
          name=$(jq --argjson number_of_days "$number_of_days" '.data.features[$number_of_days].properties.nom' coiffeurs.json | tr -d '"')
          city=$(jq --argjson number_of_days "$number_of_days" '.data.features[$number_of_days].properties.ville' coiffeurs.json | tr -d '"')

          # Output the city and name using GITHUB_OUTPUT
          echo "name=$name" >> $GITHUB_OUTPUT
          echo "city=$city" >> $GITHUB_OUTPUT
      shell: bash