name: Extract Hair Salon Infos
description: Extracts the city and name of the hair salon
inputs:
  index:
    description: Index of the hair salon
    required: true
outputs:
  name:
    description: The name of the hair salon
    value: ${{ steps.extract-hair-salon-infos.outputs.name }}
  city:
    description: The city of the hair salon
    value: ${{ steps.extract-hair-salon-infos.outputs.city }}
  zipCode:
    description: The zip code of the hair salon
    value: ${{ steps.extract-hair-salon-infos.outputs.zipCode }}
  lat:
    description: The lat of the hair salon
    value: ${{ steps.extract-hair-salon-infos.outputs.lat }}
  lng:
    description: The longitute of the hair salon
    value: ${{ steps.extract-hair-salon-infos.outputs.lng }}
runs:
  using: composite
  steps:
    - name: Execute script
      id: extract
      run: |
          start_date="2024-01-28"
          current_date=$(date +%Y-%m-%d)
          number_of_days=$(($(($(date -u -d "$current_date" +"%s") - $(date -u -d "$start_date" +"%s"))) / 86400))
        
          echo "Number of days since $start_date: $number_of_days"
          
          name=$(jq --argjson number_of_days "$number_of_days" '.data.features[$number_of_days].properties.nom' coiffeurs.json | tr -d '"')
          city=$(jq --argjson number_of_days "$number_of_days" '.data.features[$number_of_days].properties.ville' coiffeurs.json | tr -d '"')
          zipCode=$(jq --argjson number_of_days "$number_of_days" '.data.features[$number_of_days].properties.codepostal' coiffeurs.json | tr -d '"')

          lat=$(jq --argjson number_of_days "$number_of_days" '.data.features[$number_of_days].properties.lat' coiffeurs.json)
          lng=$(jq --argjson number_of_days "$number_of_days" '.data.features[$number_of_days].properties.lng' coiffeurs.json)

          echo "$name, $city, $zipCode, $lat, $lng"

          echo "name=$name" >> $GITHUB_OUTPUT
          echo "city=$city" >> $GITHUB_OUTPUT
          echo "zipCode=$zipCode" >> $GITHUB_OUTPUT

          echo "lat=$lat" >> $GITHUB_OUTPUT
          echo "lng=$lng" >> $GITHUB_OUTPUT
      shell: bash